name: Zip Files

on:
  push:
    tags:
      - '*'
jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: ${{ github.workspace }}dist/
          recursive: false
          dest: notion-word-count.zip
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: notion-word-count.zip
          asset_name: notion-word-count.zip
          tag: ${{ github.ref }}
          overwrite: true

