name: Zip Files

on:
  push:
    tags:
      - '*'
jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: "npm i"
      - run: "npm run build"
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r notion-word-count.zip ${{ github.workspace }}
      - run: "ls -la  ${{ github.workspace }}"
      - run: "ls -la  ${{ github.workspace }}/dist"
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: notion-word-count.zip
          asset_name: notion-word-count.zip
          tag: ${{ github.ref }}
          overwrite: true

